# Generated by Django 3.2.5 on 2021-12-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('HM', 'Humanidades'), ('TF', 'Técnico y formación'), ('MI', 'Métodos de idiomas'), ('LI', 'Literatura'), ('CM', 'Cómic y manga'), ('JU', 'Juvenil'), ('AR', 'Artes'), ('FI', ' Filología'), ('OC', 'Ocio'), ('CO', 'Cocina'), ('FA', 'Fantasía'), ('MT', 'Misterio y thriller')], default='CO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField(default=0.0)),
                ('hidden', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=product.models.path_and_rename)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
    ]
